# Generated by Django 6.0.5 on 2026-05-28 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На рассмотрении'), ('invited', 'Приглашен'), ('rejected', 'Отклонен'), ('approved', 'Утвержден')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской'), ('other', 'Другое')], max_length=20, verbose_name='Пол')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост, см')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('portfolio_link', models.URLField(blank=True, verbose_name='Портфолио')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audition_time', models.DateTimeField(verbose_name='Время пробы')),
                ('room', models.CharField(max_length=80, verbose_name='Зал/кабинет')),
                ('result_note', models.TextField(blank=True, verbose_name='Результат')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audition', to='casting.application')),
            ],
            options={
                'verbose_name': 'Расписание пробы',
                'verbose_name_plural': 'Расписание проб',
                'ordering': ['audition_time'],
            },
        ),
        migrations.CreateModel(
            name='CastingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название кастинга')),
                ('client', models.CharField(max_length=160, verbose_name='Заказчик')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=160, verbose_name='Локация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыт'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Кастинг',
                'verbose_name_plural': 'Кастинги',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='casting.castingproject'),
        ),
        migrations.CreateModel(
            name='RoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=120, verbose_name='Роль')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Требуемый пол')),
                ('min_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст от')),
                ('max_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст до')),
                ('required_skills', models.CharField(max_length=250, verbose_name='Ключевые навыки')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Гонорар')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='casting.castingproject')),
            ],
            options={
                'verbose_name': 'Требование к роли',
                'verbose_name_plural': 'Требования к ролям',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.rolerequirement'),
        ),
        migrations.AddField(
            model_name='application',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='casting.talent'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('talent', 'project', 'role')},
        ),
    ]
